### PR TITLE
All Unicode Converters -repull

### PR DESCRIPTION
**Pull request by abuvanth**

### CODE REVIEW

**Comment by arcturusannamalai** [comment]
Nice work, Thanks @abuvanth

**Comment by arulalant** [comment]
@abuvanth Thanks for your work. It would be nice (more user-friendly) if all unicode / encode names as radio buttons instead of dropdown button. For example see here http://kandupidi.com/converter/ and http://www.suratha.com/reader.htm along with auto find encoding convertor.

**Comment by arcturusannamalai** [comment]
@arulalant - I think its already hosted http://tamilpesu.us

**Comment by arulalant** [comment]
yes, it is hosted. But I suggested to make it as radio button rather than a dropdown list (when it really huge list 30+ encodes).

**Pull request merged**
